### ISSUE TITLE
vue+webpack4.x 使用该插件后，未完全移除，且会把原有的console.log改为","

### ISSUE THREAD

**Issue by hauk0101** [Rise-Devin/drop-console-webpack-plugin#1]
项目环境：
webpack 4.20.2
vue 2.5.2
node 8.11.3
npm 5.6.0
"drop-console-webpack-plugin": "^3.0.2"

使用结果：
1.不能完全把 console.log() 移除
2.移除的 console.log() 都会被 ","替换，引发一些其他问题

**Comment by AwesomeDevin** [comment]
我看一下

**Comment by AwesomeDevin** [comment]
webpack4 请使用 drop-console-webpack-plugin@4.0.2    
3.0.2 是用以支持webpack4以下的
谢谢

**Comment by zhuchaoyang** [comment]
4.0.2 没用，会转成两个逗号

**Comment by AwesomeDevin** [comment]
> 4.0.2 没用，会转成两个逗号

可能是第三方库的一些影响,有些库中console语句不属于log，导致报错,需要将第三方库分别打包(如name为manifest)，然后加到exclude属性中
```
new DropConsoleWebpackPlugin({
    drop_log    : true, 
    drop_info   : true,
    drop_warn   : false,
    drop_error  : false,
    exclude     : ['manifest'],      
})
```

**Comment by ramwin** [comment]
我也遇到了这个问题, 打包后报错
webpack 4.28.4  
drop-console-webpack-plugin 4.0.2
```
Uncaught SyntaxError: Unexpected token ','
```
